# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Trucco\'s notes'
tagline:             'Las notas de Trucco'
description:         'Arbitrary Computer Science notes.'
url:                 https://frantrucco.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Francisco Trucco
  url:               https://twitter.com/frantrucco95
  email:             franciscoctrucco@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
